"""empty message

Revision ID: 249040a32acd
Revises: d00234f6ccef
Create Date: 2023-05-13 18:10:16.816078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249040a32acd'
down_revision = 'd00234f6ccef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'punk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('punk', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
