"""empty message

Revision ID: 26ad9b57b0f3
Revises: 7ee135bc3b88
Create Date: 2023-05-13 18:15:59.979569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26ad9b57b0f3'
down_revision = '7ee135bc3b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'user_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('roles', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
