"""empty message

Revision ID: 7b2d225b948c
Revises: 802f455648f2
Create Date: 2023-05-13 17:47:46.933482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2d225b948c'
down_revision = '802f455648f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###
