"""empty message

Revision ID: 802f455648f2
Revises: b04d13987896
Create Date: 2023-05-13 16:45:48.262595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802f455648f2'
down_revision = 'b04d13987896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('user_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image_url')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
