"""empty message

Revision ID: d00234f6ccef
Revises: a5c6f9fbb0f1
Create Date: 2023-05-13 18:09:24.742685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00234f6ccef'
down_revision = 'a5c6f9fbb0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('punk', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'punk')
    # ### end Alembic commands ###
