"""empty message

Revision ID: f4e0a02649dd
Revises: 26ad9b57b0f3
Create Date: 2023-05-13 18:16:13.576314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e0a02649dd'
down_revision = '26ad9b57b0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('user_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image_url')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
